"""Pydantic schemas for Hinge API responses.

Pure data models — no client references, no Active Record pattern.

This package groups the schemas by domain across submodules and re-exports
every public class here so ``from hinge.models import X`` keeps working for
all historical names.
"""

from hinge.models.attributes import (
    BoundingBox,
    ChildrenStatus,
    DatingIntention,
    DrinkingStatus,
    DrugStatus,
    Educations,
    Ethnicities,
    FamilyPlans,
    GenderIdentity,
    HomeTown,
    JobTitle,
    Language,
    MarijuanaStatus,
    Pets,
    Politics,
    RelationshipType,
    Religion,
    SexualOrientation,
    SmokingStatus,
    Works,
)
from hinge.models.auth import HingeAuthToken, SendbirdAuthToken
from hinge.models.base import BaseHingeModel
from hinge.models.content import (
    AnswerContent,
    AnswerContentPayload,
    ContentSettings,
    Feedback,
    PhotoContent,
    ProfileContent,
    ProfileContentContent,
    PromptEvaluation,
    SelfContentResponse,
    TextAnswer,
    TranscriptionMetadata,
    VideoDetail,
)
from hinge.models.preferences import (
    Dealbreakers,
    GenderedDealbreaker,
    GenderedRange,
    Preferences,
    RangeDetails,
)
from hinge.models.profile import (
    Location,
    Profile,
    ProfileV2,
    SelfProfileResponse,
    UserProfile,
    UserProfileV2,
)
from hinge.models.prompts import (
    DateIdeaContent,
    Prompt,
    PromptCategory,
    PromptContent,
    PromptsResponse,
    VideoPromptContent,
)
from hinge.models.rating import (
    CreateRate,
    CreateRateContent,
    CreateRateContentPrompt,
    HiddenLike,
    LikeImpression,
    LikeLimit,
    LikeResponse,
    LikeSortCategory,
    LikesYouResponse,
    MatchRate,
    RatePhoto,
    RespondRate,
    SortedLikes,
)
from hinge.models.recommendations import (
    Enhancements,
    RecommendationSubject,
    RecommendationsFeed,
    RecommendationsResponse,
    SecondChance,
    TextReview,
)
from hinge.models.standouts import (
    StandoutContent,
    StandoutPhoto,
    StandoutSubject,
    StandoutsV2Response,
    StandoutsV3Response,
)

__all__ = [
    "AnswerContent",
    "AnswerContentPayload",
    "BaseHingeModel",
    "BoundingBox",
    "ChildrenStatus",
    "ContentSettings",
    "CreateRate",
    "CreateRateContent",
    "CreateRateContentPrompt",
    "DateIdeaContent",
    "DatingIntention",
    "Dealbreakers",
    "DrinkingStatus",
    "DrugStatus",
    "Educations",
    "Enhancements",
    "Ethnicities",
    "FamilyPlans",
    "Feedback",
    "GenderIdentity",
    "GenderedDealbreaker",
    "GenderedRange",
    "HiddenLike",
    "HingeAuthToken",
    "HomeTown",
    "JobTitle",
    "Language",
    "LikeImpression",
    "LikeLimit",
    "LikeResponse",
    "LikeSortCategory",
    "LikesYouResponse",
    "Location",
    "MarijuanaStatus",
    "MatchRate",
    "Pets",
    "PhotoContent",
    "Politics",
    "Preferences",
    "Profile",
    "ProfileContent",
    "ProfileContentContent",
    "ProfileV2",
    "Prompt",
    "PromptCategory",
    "PromptContent",
    "PromptEvaluation",
    "PromptsResponse",
    "RangeDetails",
    "RatePhoto",
    "RecommendationSubject",
    "RecommendationsFeed",
    "RecommendationsResponse",
    "RelationshipType",
    "Religion",
    "RespondRate",
    "SecondChance",
    "SelfContentResponse",
    "SelfProfileResponse",
    "SendbirdAuthToken",
    "SexualOrientation",
    "SmokingStatus",
    "SortedLikes",
    "StandoutContent",
    "StandoutPhoto",
    "StandoutSubject",
    "StandoutsV2Response",
    "StandoutsV3Response",
    "TextAnswer",
    "TextReview",
    "TranscriptionMetadata",
    "UserProfile",
    "UserProfileV2",
    "VideoDetail",
    "VideoPromptContent",
    "Works",
]
