"""Hinge profile table definition."""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Table,
    func,
)

from hinge.infrastructure.db.metadata import metadata
from hinge.infrastructure.db.types import JsonList

hinge_profile_table = Table(
    "hinge_profiles",
    metadata,
    Column("subject_id", String, primary_key=True),
    Column("first_name", String, nullable=False),
    Column("age", Integer),
    Column("gender_id", Integer),
    Column("height", Integer),
    Column("location_name", String),
    Column("latitude", Float),
    Column("longitude", Float),
    Column("hometown", String),
    Column("job_title", String),
    Column("works", String),
    Column("education_attained", Integer),
    Column("selfie_verified", Boolean, default=False),
    Column("did_just_join", Boolean, default=False),
    Column("last_active_status_id", Integer),
    Column("children", Integer),
    Column("dating_intention", Integer),
    Column("dating_intention_text", String),
    Column("drinking", Integer),
    Column("drugs", Integer),
    Column("marijuana", Integer),
    Column("smoking", Integer),
    Column("family_plans", Integer),
    Column("politics", Integer),
    Column("religions", JsonList),
    Column("ethnicities", JsonList),
    Column("ethnicities_text", String),
    Column("relationship_types", JsonList),
    Column("relationship_types_text", String),
    Column("languages_spoken", JsonList),
    Column("pets", JsonList),
    Column("zodiac", Integer),
    Column("educations", String),
    Column("last_active_status", String),
    Column("photo_urls", JsonList),
    Column("first_seen_at", DateTime, nullable=False, server_default=func.now()),
    Column("last_seen_at", DateTime, nullable=False, server_default=func.now()),
    Column("times_seen", Integer, nullable=False, default=1),
    Column("source", String),
    Column("likely_rejected", Boolean, default=False),
    Column("rejection_detected_at", DateTime),
    Column("rejection_type", String),
    Column("miss_count", Integer, nullable=False, default=0),
    # Rating context for like/skip API calls
    Column("rating_token", String),
    Column("origin", String),
)
